spring.application.name=back-end

spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.checkin.hmacSecret=gffuygih

server.port=8080

spring.security.oauth2.client.registration.google.client-id=841328929061-0bguqt2ocsbtp87oqjmvt99oqkv4868f.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

app.admin.email=paflogin8@gmail.com
app.admin.name=pafLogin@321#


app.jwt.secret=1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
app.jwt.expiration-ms=86400000